#!/usr/bin/expect -f
set timeout 120
set password "12345Surabaya"

set ips {
    "157.230.57.107"
    "134.209.70.199"
    "68.183.118.125"
    "104.248.114.10"
    "137.184.216.19"
    "137.184.73.76"
}

foreach ip $ips {
    puts "Deploying tools to $ip..."
    spawn scp -o StrictHostKeyChecking=no build_tools/cms-scan build_tools/wp-plugins-detector build_tools/cnc-enum root@$ip:/root/cnc-worker-node/tools/
    expect {
        "*assword:*" {
            send "$password\r"
            exp_continue
        }
        eof
    }
}
